global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'qwen-agent'
    static_configs:
      - targets: ['qwen-agent-chat:5001']
    metrics_path: '/health'
    scrape_interval: 30s

  - job_name: 'playwright-service'
    static_configs:
      - targets: ['playwright-service:3000']
    metrics_path: '/health'
    scrape_interval: 30s
